[project]
name = "python-crawl"
version = "0.1.0"
description = "職能發展學院phthon視窗網路爬蟲"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crawl4ai>=0.7.7",
    "ipykernel>=7.1.0",
    "playwright>=1.56.0",
]
